---
- name: Update apt cache
  apt:
    upgrade: no
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Ensure Java is installed.
  apt: "name={{ item }} state=present"
  with_items: "{{ java_packages }}"
